name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # required for AWS OIDC

jobs:
  apply:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::265088867231:role/github/tf-via-github-demo

      - name: Terraform init and validate
        run: |
          terraform init -backend-config="key=terraform.tfstate" -backend-config="bucket=stwalkerster-265088867231-demo-tfstate" -backend-config="dynamodb_table=stwalkerster-265088867231-demo-tfstatelock"

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out tfplan
      
      - name: Terraform Apply
        run: terraform apply tfplan